import { FileText, Shield, Heart, Receipt, Building2, Landmark, Home, HardHat, BadgeIndianRupee } from "lucide-react";

export interface ServiceData {
  id: string;
  icon: typeof FileText;
  titleEn: string;
  titleTe: string;
  descEn: string;
  descTe: string;
  modalBodyEn: string;
  modalBodyTe: string;
  eligibilityEn?: string;
  eligibilityTe?: string;
  documentsEn?: string[];
  documentsTe?: string[];
  externalLink: string | null;
  buttonLabel: string;
  phone?: string;
  customCallLabelEn?: string;
  customCallLabelTe?: string;
  customWhatsappLabelEn?: string;
  customWhatsappLabelTe?: string;
}

export const services: ServiceData[] = [
  {
    id: "home-loans",
    icon: Landmark,
    titleEn: "Home Loans all Nationalized Banks",
    titleTe: "అన్ని జాతీయ బ్యాంకుల గృహ రుణాలు",
    descEn: "Get Home Loans from all Nationalized Banks with Best Interest Rates.",
    descTe: "అన్ని జాతీయ బ్యాంకుల కోసం గృహ రుణాలు పొందండి.",
    modalBodyEn: "We provide hassle-free home loans from all nationalized banks with the best interest rates. Get complete guidance on documentation, processing, and seamless loan approval.",
    modalBodyTe: "మేము అన్ని జాతీయ బ్యాంకుల నుండి సులభమైన మరియు వేగవంతమైన గృహ రుణాలను అందిస్తాము. కనీస డాక్యుమెంటేషన్‌తో ఉత్తమ వడ్డీ రేట్లను పొందండి. మొత్తం రుణ ప్రక్రియలో మేము మీకు మార్గనిర్దేశం చేస్తాము.",
    externalLink: null,
    buttonLabel: "Contact Now",
  },
  {
    id: "general-insurance",
    icon: Shield,
    titleEn: "General insurance ICICI bank",
    titleTe: "జనరల్ ఇన్సూరెన్స్ ICICI బ్యాంక్",
    descEn: "General insurance services from ICICI Bank.",
    descTe: "ICICI బ్యాంక్ నుండి జనరల్ ఇన్సూరెన్స్ సేవలు.",
    modalBodyEn: "Secure your future with comprehensive general insurance services from ICICI Bank. We offer various policies including health, vehicle, and property insurance to protect what matters to you.",
    modalBodyTe: "ICICI బ్యాంక్ నుండి జనరల్ ఇన్సూరెన్స్ సేవలతో మీ భవిష్యత్తును సురక్షితం చేసుకోండి. మేము ఆరోగ్యం, వాహనం మరియు ఆస్తి బీమా వంటి వివిధ పాలసీలను అందిస్తాము.",
    externalLink: null,
    buttonLabel: "Contact Now",
  },
  {
    id: "pmegp-loans",
    icon: BadgeIndianRupee,
    titleEn: "PMEGP Loans",
    titleTe: "PMEGP రుణాలు",
    descEn: "Government-backed loans for new small businesses. Up to ₹25 lakh for manufacturing, up to ₹10 lakh for services.",
    descTe: "కొత్త చిన్న వ్యాపారాల కోసం ప్రభుత్వ మద్దతు రుణాలు. తయారీకి ₹25 లక్షల వరకు, సేవలకు ₹10 లక్షల వరకు.",
    modalBodyEn: "PMEGP (Prime Minister Employment Generation Programme) is a Government of India scheme that provides subsidised loans to help people start new small businesses. Easy Home Projects helps you with the full application — from project report writing to bank submission.",
    modalBodyTe: "PMEGP (ప్రధాన మంత్రి ఉపాధి కల్పన కార్యక్రమం) అనేది కొత్త చిన్న వ్యాపారాలను ప్రారంభించడంలో సహాయపడే భారత ప్రభుత్వ పథకం. ఈజీ హోమ్ ప్రాజెక్ట్స్ మీ పూర్తి దరఖాస్తులో సహాయపడుతుంది.",
    eligibilityEn: "Any Indian citizen above 18 years. For projects above ₹10 lakh (manufacturing) or ₹5 lakh (service), minimum 8th class pass required.",
    eligibilityTe: "18 సంవత్సరాల కంటే ఎక్కువ వయస్సు ఉన్న ఏ భారతీయ పౌరుడైనా. ₹10 లక్షల (తయారీ) పైన ప్రాజెక్ట్ల కోసం కనీసం 8వ తరగతి ఉత్తీర్ణత అవసరం.",
    documentsEn: ["Aadhaar", "PAN", "Address Proof", "Educational Certificate", "Project Report (we prepare this)", "Caste Certificate if applicable"],
    documentsTe: ["ఆధార్", "PAN", "చిరునామా రుజువు", "విద్యా ధృవీకరణ పత్రం", "ప్రాజెక్ట్ రిపోర్ట్ (మేము తయారు చేస్తాము)", "కులం ధృవీకరణ పత్రం (వర్తిస్తే)"],
    externalLink: "https://www.kviconline.gov.in/pmegpeportal/pmegphome/index.jsp",
    buttonLabel: "Apply on KVIC Portal →",
  },
  {
    id: "mudra-loans",
    icon: BadgeIndianRupee,
    titleEn: "Mudra Loans",
    titleTe: "ముద్ర రుణాలు",
    descEn: "Pradhan Mantri Mudra Yojana (PMMY) loans up to ₹10 lakh for micro and small businesses.",
    descTe: "సూక్ష్మ మరియు చిన్న వ్యాపారాల కోసం ₹10 లక్షల వరకు ముద్ర రుణాలు.",
    modalBodyEn: "Mudra Loans (PMMY) are available to small business owners, traders, and micro-enterprises. Categories: Shishu (up to ₹50,000), Kishore (₹50,001 to ₹5 lakh), Tarun (₹5 lakh to ₹10 lakh).",
    modalBodyTe: "ముద్ర రుణాలు చిన్న వ్యాపార యజమానులు, వ్యాపారులు మరియు సూక్ష్మ సంస్థలకు అందుబాటులో ఉన్నాయి.",
    eligibilityEn: "Non-corporate, non-farm small/micro business owners. No collateral required for Shishu and Kishore.",
    eligibilityTe: "కార్పొరేట్ కాని, వ్యవసాయేతర చిన్న/సూక్ష్మ వ్యాపార యజమానులు.",
    documentsEn: ["Aadhaar", "PAN", "Business Proof", "Address Proof", "Bank Statements (6 months)", "Passport Photo"],
    documentsTe: ["ఆధార్", "PAN", "వ్యాపార రుజువు", "చిరునామా రుజువు", "బ్యాంక్ స్టేట్‌మెంట్లు (6 నెలలు)", "పాస్‌పోర్ట్ ఫోటో"],
    externalLink: "https://www.mudra.org.in",
    buttonLabel: "Apply on Mudra Portal →",
  },
  {
    id: "hdfc-life",
    icon: Shield,
    titleEn: "HDFC Life Insurance",
    titleTe: "HDFC లైఫ్ ఇన్సూరెన్స్",
    descEn: "Authorised HDFC Life Insurance plans in Kadapa. Term plans, savings plans, and pension plans.",
    descTe: "కడపలో అధికారిక HDFC లైఫ్ ఇన్సూరెన్స్ ప్లాన్లు.",
    modalBodyEn: "As an authorised HDFC Life Insurance partner, K. Praveen Kumar Reddy helps you choose the right life insurance plan. Whether you need a term plan or a savings plan — we guide you honestly with no pressure.",
    modalBodyTe: "అధికారిక HDFC లైఫ్ ఇన్సూరెన్స్ భాగస్వామిగా, K. ప్రవీణ్ కుమార్ రెడ్డి మీకు సరైన ప్లాన్ ఎంచుకోవడంలో సహాయపడతారు.",
    externalLink: "https://www.hdfclife.com",
    buttonLabel: "Visit HDFC Life Website →",
  },
  {
    id: "care-health",
    icon: Heart,
    titleEn: "Care Health Insurance",
    titleTe: "కేర్ హెల్త్ ఇన్సూరెన్స్",
    descEn: "Authorised Care Health Insurance agent in Kadapa. Individual and family floater health plans.",
    descTe: "కడపలో అధికారిక కేర్ హెల్త్ ఇన్సూరెన్స్ ఏజెంట్.",
    modalBodyEn: "Easy Home Projects is an authorised partner for Care Health Insurance. We help you choose a plan that covers hospitalisation, pre and post hospitalisation, daycare procedures, and more.",
    modalBodyTe: "ఈజీ హోమ్ ప్రాజెక్ట్స్ కేర్ హెల్త్ ఇన్సూరెన్స్ అధికారిక భాగస్వామి.",
    externalLink: "https://www.careinsurance.com",
    buttonLabel: "Visit Care Health Website →",
  },
  {
    id: "gst-tax",
    icon: Receipt,
    titleEn: "GST Registration & Returns",
    titleTe: "GST రిజిస్ట్రేషన్ & రిటర్న్స్",
    descEn: "Get your GSTIN, file monthly/quarterly returns, and stay GST-compliant in Andhra Pradesh.",
    descTe: "మీ GSTIN పొందండి, నెలవారీ/త్రైమాసిక రిటర్న్లు దాఖలు చేయండి.",
    modalBodyEn: "Easy Home Projects handles GST registration and all return filings — GSTR-1, GSTR-3B, GSTR-9 — on time. No penalties, no confusion.",
    modalBodyTe: "ఈజీ హోమ్ ప్రాజెక్ట్స్ GST రిజిస్ట్రేషన్ మరియు అన్ని రిటర్న్ ఫైలింగ్‌లను సమయానికి నిర్వహిస్తుంది.",
    externalLink: "https://www.gst.gov.in",
    buttonLabel: "GST Portal (Official) →",
  },
  {
    id: "income-tax",
    icon: FileText,
    titleEn: "Income Tax Return (ITR)",
    titleTe: "ఆదాయపు పన్ను రిటర్న్ (ITR)",
    descEn: "ITR filing for individuals, salaried employees, and business owners in Kadapa and Gooty.",
    descTe: "కడప మరియు గూటీలో వ్యక్తులు, జీతభత్యాల ఉద్యోగులు మరియు వ్యాపార యజమానుల కోసం ITR దాఖలు.",
    modalBodyEn: "Filing your Income Tax Return every year is mandatory. Easy Home Projects files your ITR accurately and on time. We handle ITR-1, ITR-2, ITR-3, ITR-4, and audit cases. TDS returns are also filed.",
    modalBodyTe: "ప్రతి సంవత్సరం మీ ఆదాయపు పన్ను రిటర్న్ దాఖలు చేయడం తప్పనిసరి. ఈజీ హోమ్ ప్రాజెక్ట్స్ మీ ITRను ఖచ్చితంగా మరియు సమయానికి దాఖలు చేస్తుంది.",
    externalLink: "https://www.incometax.gov.in",
    buttonLabel: "IT Department Portal →",
  },
  {
    id: "pvt-ltd-reg",
    icon: Building2,
    titleEn: "Pvt Ltd Company Registration",
    titleTe: "ప్రైవేట్ లిమిటెడ్ కంపెనీ రిజిస్ట్రేషన్",
    descEn: "Fast and hassle-free Private Limited company registration.",
    descTe: "ఆంధ్ర ప్రదేశ్‌లో ప్రైవేట్ లిమిటెడ్ కంపెనీ రిజిస్ట్రేషన్.",
    modalBodyEn: "We handle complete end-to-end Private Limited company registration including Name Approval, DSC, DIN, MOA, and AOA. Start your startup correctly without any hassle.",
    modalBodyTe: "మేము ప్రైవేట్ లిమిటెడ్ కంపెనీ రిజిస్ట్రేషన్‌ను నిర్వహిస్తాము.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "public-company-reg",
    icon: Building2,
    titleEn: "Public Company Registration",
    titleTe: "పబ్లిక్ కంపెనీ రిజిస్ట్రేషన్",
    descEn: "End-to-end assistance for registering a Public Limited Company.",
    descTe: "పబ్లిక్ కంపెనీ రిజిస్ట్రేషన్‌కు పూర్తి సహాయం.",
    modalBodyEn: "Looking to raise capital from the public? We provide complete assistance in registering your Public Limited Company, setting up the board of directors, and fulfilling all MCA compliance requirements.",
    modalBodyTe: "పబ్లిక్ లిమిటెడ్ కంపెనీని నమోదు చేయడంలో మేము పూర్తి సహాయం అందిస్తున్నాము.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "opc-company-reg",
    icon: Building2,
    titleEn: "OPC Company Registration",
    titleTe: "OPC కంపెనీ రిజిస్ట్రేషన్",
    descEn: "One Person Company (OPC) registration made easy for solo founders.",
    descTe: "సోలో వ్యవస్థాపకుల కోసం వన్ పర్సన్ కంపెనీ (OPC) రిజిస్ట్రేషన్ సులభం చేయబడింది.",
    modalBodyEn: "One Person Company is the perfect structure for solo entrepreneurs looking for limited liability protection. We handle the complete setup documentation smoothly.",
    modalBodyTe: "ఒక వ్యక్తి కంపెనీ (OPC) అనేది సోలో వ్యవస్థాపకులకు సరైన నిర్మాణం.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "society-reg",
    icon: Building2,
    titleEn: "Society Registration",
    titleTe: "సొసైటీ రిజిస్ట్రేషన్",
    descEn: "Seamless NGO, Trust, and Society registration services.",
    descTe: "హ్యాసిల్ ఫ్రీ NGO, ట్రస్ట్ మరియు సొసైటీ రిజిస్ట్రేషన్ సేవలు.",
    modalBodyEn: "Want to start a non-profit or society? We manage all documentation, drafting rules and regulations, and submitting it to the registrar securely.",
    modalBodyTe: "లాభాపేక్షలేని లేదా సొసైటీని ప్రారంభించాలనుకుంటున్నారా? మేము డాక్యుమెంటేషన్‌ను నిర్వహిస్తాము.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "roc-filings",
    icon: FileText,
    titleEn: "ROC Filings",
    titleTe: "ROC ఫైలింగ్స్",
    descEn: "Annual MCA and ROC compliance filing for companies.",
    descTe: "కంపెనీల కోసం వార్షిక MCA మరియు ROC ఫైలింగ్.",
    modalBodyEn: "Every private and public company must file its annual returns with the Registrar of Companies. Easy Home Projects helps you file AOC-4, MGT-7, and director KYC on time to avoid huge penalties.",
    modalBodyTe: "ప్రతి కంపెనీ రిజిస్ట్రార్ ఆఫ్ కంపెనీస్‌తో వార్షిక రిటర్న్‌లను ఫైల్ చేయాలి.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "tax-audit",
    icon: Receipt,
    titleEn: "Tax Audit Filings",
    titleTe: "టాక్స్ ఆడిట్ ఫైలింగ్స్",
    descEn: "Tax Audit Report filing for eligible businesses and professionals.",
    descTe: "వ్యాపారాలు మరియు నిపుణుల కోసం టాక్స్ ఆడిట్ రిపోర్ట్ ఫైలింగ్.",
    modalBodyEn: "If your business turnover exceeds the threshold, a tax audit is mandatory under section 44AB. We offer comprehensive tax audit filing directly with certified professionals to ensure full compliance.",
    modalBodyTe: "ఈజీ హోమ్ ప్రాజెక్ట్స్ పన్ను ఆడిట్ ఫైలింగ్ అందిస్తుంది.",
    externalLink: null,
    buttonLabel: "Contact Praveen Directly",
  },
  {
    id: "real-estate",
    icon: Home,
    titleEn: "Real Estate Advisory",
    titleTe: "రియల్ ఎస్టేట్ సలహా",
    descEn: "Trusted real estate consultancy in Kadapa and Gooty. Buy, sell, or invest in property.",
    descTe: "కడప మరియు గూటీలో నమ్మకమైన రియల్ ఎస్టేట్ సలహా.",
    modalBodyEn: "Looking to buy, sell, or invest in property? Easy Home Projects provides honest property advisory — no inflated prices, no middlemen charges.",
    modalBodyTe: "ఆస్తి కొనడానికి, అమ్మడానికి లేదా పెట్టుబడి పెట్టడానికి చూస్తున్నారా? ఈజీ హోమ్ ప్రాజెక్ట్స్ నిజాయితీ ఆస్తి సలహాను అందిస్తుంది.",
    externalLink: null,
    buttonLabel: "Contact Now",
    phone: "6301454303",
    customCallLabelEn: "Call",
    customCallLabelTe: "కాల్",
    customWhatsappLabelEn: "WhatsApp",
    customWhatsappLabelTe: "WhatsApp",
  },
  {
    id: "construction",
    icon: HardHat,
    titleEn: "Construction Consultancy",
    titleTe: "నిర్మాణ సలహా",
    descEn: "Construction planning and consultancy services in Kadapa. Budget, design, and execution guidance.",
    descTe: "కడపలో నిర్మాణ ప్రణాళిక మరియు సలహా సేవలు.",
    modalBodyEn: "Planning a house, commercial building, or renovation project? Easy Home Projects provides construction consultancy — helping you plan the budget, work with contractors, and manage the project smoothly.",
    modalBodyTe: "ఇల్లు, వాణిజ్య భవనం లేదా పునరుద్ధరణ ప్రాజెక్ట్ ప్లాన్ చేస్తున్నారా? ఈజీ హోమ్ ప్రాజెక్ట్స్ నిర్మాణ సలహాను అందిస్తుంది.",
    externalLink: null,
    buttonLabel: "Contact Now",
    phone: "6301454303",
    customCallLabelEn: "Call",
    customCallLabelTe: "కాల్",
    customWhatsappLabelEn: "WhatsApp",
    customWhatsappLabelTe: "WhatsApp",
  },
];
